const itemsData = [
  {
    imagePath: "src/img/menus/menu1.png",
    name: "Spaghetti alla Carbonara",
    description: "Massa al dente com um molho cremoso de ovos, queijo Pecorino, guanciale e pimenta preta.",
    category: "massas",
    rating: 9,
    price: 42.50,
  },
  {
    imagePath: "./src/img/menus/menu2.png",
    name: "Lasanha à Bolonhesa",
    description: "Camadas de massa intercaladas com ragu de carne moída, molho bechamel e queijo parmesão gratinado.",
    category: "massas",
    rating: 9,
    price: 45.00,
  },
  {
    imagePath: "./src/img/menus/menu3.png",
    name: "Penne all'Arrabbiata",
    description: "Penne em um molho de tomate picante com alho e pimenta calabresa, um clássico de Roma.",
    category: "massas",
    rating: 8,
    price: 38.00,
  },
  {
    imagePath: "./src/img/menus/menu4.png",
    name: "Fettuccine Alfredo",
    description: "Fettuccine fresco envolvido em um molho aveludado de manteiga e queijo Parmigiano-Reggiano.",
    category: "massas",
    rating: 8,
    price: 39.90,
  },
  {
    imagePath: "./src/img/menus/menu5.png",
    name: "Ravioli di Ricotta e Spinaci",
    description: "Raviolis artesanais recheados com ricota fresca e espinafre, servidos na manteiga e sálvia.",
    category: "massas",
    rating: 9,
    price: 44.00,
  },
  {
    imagePath: "./src/img/menus/menu6.png",
    name: "Gnocchi al Pesto Genovese",
    description: "Nhoques de batata macios cobertos com molho pesto tradicional de manjericão, pinhões e alho.",
    category: "massas",
    rating: 8,
    price: 41.50,
  },
  {
    imagePath: "./src/img/menus/menu3.png",
    name: "Cacio e Pepe",
    description: "Uma receita romana simples e elegante com queijo Pecorino Romano e pimenta do reino moída na hora.",
    category: "massas",
    rating: 9,
    price: 37.90,
  },
  {
    imagePath: "./src/img/menus/menu3.png",
    name: "Spaghetti al Ragù",
    description: "O clássico espaguete servido com um rico e saboroso ragu de carne cozido lentamente por horas.",
    category: "massas",
    rating: 9,
    price: 40.00,
  },
];

export default itemsData;